files:
  - source: /
    translation: /%two_letters_code%/%original_file_name%

"files" : [
  {
    "source" : "/*.resx",
    "dest" : "/*csv",
    "translation" : "/conf/messages.%two_letters_code%",
    "type" : "properties"
  }
]
